// <auto-generated />
using System;
using LearnOneProvincesVN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnOneProvincesVN.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231005081815_updateDB")]
    partial class updateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Districts", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Districs_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Districts_Name");

                    b.Property<int?>("Provinces_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Provinces_ID");

                    b.HasKey("ID");

                    b.HasIndex("Provinces_ID");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Provinces", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Provinces_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Provinces_Name");

                    b.HasKey("ID");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Wards", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("Districts_ID")
                        .HasColumnType("integer")
                        .HasColumnName("Districts_ID");

                    b.Property<string>("Wards_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Wards_Name");

                    b.HasKey("ID");

                    b.HasIndex("Districts_ID");

                    b.ToTable("Wards", (string)null);
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Districts", b =>
                {
                    b.HasOne("LearnOneProvincesVN.Data.Entity.Provinces", "Provinces")
                        .WithMany("Districts")
                        .HasForeignKey("Provinces_ID");

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Wards", b =>
                {
                    b.HasOne("LearnOneProvincesVN.Data.Entity.Districts", "Districts")
                        .WithMany("Wards")
                        .HasForeignKey("Districts_ID");

                    b.Navigation("Districts");
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Districts", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("LearnOneProvincesVN.Data.Entity.Provinces", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
